version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "8000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      #https://learn.microsoft.com/en-us/aspnet/core/security/docker-compose-https?view=aspnetcore-8.0: will not support HTTPS in this configuration
      - ASPNETCORE_URLS=http://+:80
      - CatsStealer_ConnectionString=${DB_CONNECTION_STRING}
      - CatsStealer_CatsApiSettings:ApiKey=${CATS_API_KEY}
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: